version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.34.0
    steps:
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - checkout
      - restore_cache:
          key: target
      - run:
          name: build
          command: cargo build
      - run:
          name: test
          command: cargo test
      - save_cache:
          # TODO: consider only saving part of target, or making the key a function of Cargo.lock.
          key: "target"
          paths:
            - "./target"
