version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.34.0
    steps:
      - checkout
      - restore_cache:
          key: target
      - run:
          name: build
          command: cargo build
      - run:
          name: test
          command: cargo test
      - save_cache:
          key: "target"
          paths:
            - "./target"
