version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.34.2
    steps:
      - restore_cache:
          name: Restoring tools cache
          key: cargo_1_34_2
      - run:
          name: Install tools
          command: rustup component add rustfmt
      - save_cache:
          name: Saving tools cache
          key: "cargo_1_34_2"
          paths:
            - "~/.cargo"
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version && cargo fmt --version
      - checkout
      - restore_cache:
          key: target
      - run:
          name: format
          command: cargo fmt && git diff --exit-code
      - run:
          name: build
          command: cargo build
      - run:
          name: test
          command: cargo test
      - save_cache:
          # TODO: consider only saving part of target, or making the key a function of Cargo.lock.
          key: "target"
          paths:
            - "./target"
